; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
lib_deps =
	lovyan03/LovyanGFX@1.2.19
	links2004/WebSockets@2.7.1
build_flags =
	-I include
	-I src
	-O3
	-DINTER_MODULE_OPT
	-DCORE_DEBUG_LEVEL=0
	; Add -DGB_ENABLE_AUDIO=1 to re-enable the experimental software APU.
monitor_speed = 115200
board_build.partitions = partitions.csv
